name: Unity iOS Build (No Codesign)

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Cache Unity Library
              uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                  restore-keys: |
                      Library-

            - name: Build iOS (No Codesign)
              uses: game-ci/unity-builder@v4
              env:
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  targetPlatform: iOS
                  projectPath: .
                  customParameters: "-noCodeSign"

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: iOSBuildNoCodesign
                  path: build
